package com.example.main.simplemp3_2.Utils;

public interface MusicConstants {
    String ARGUMENTS_TOOLBAR_TITLE = "argumentsToolBarTitle";
    String ACTION_PLAY = "ACTION_PLAY";
    String ACTION_PAUSE = "ACTION_PAUSE";
    String ACTION_START = "ACTION_START";
    String ACTION_PLAY_PREV = "ACTION_PLAY_PREV";
    String ACTION_PLAY_NEXT = "ACTION_PLAY_NEXT";
    String ACTION_CONTINUE = "ACTION_CONTINUE";
    String NOTIFICATION_PLAY = "NOTIFICATION_PLAY";
    String NOTIFICATION_PAUSE = "NOTIFICATION_PAUSE";
    String NOTIFICATION_PLAY_PREV = "NOTIFICATION_PLAY_PREV";
    String NOTIFICATION_PLAY_NEXT = "NOTIFICATION_PLAY_NEXT";
    String NOTIFICATION_CLOSE_NOTIFICATION = "NOTIFICATION_CLOSE_NOTIFICATION";
    String MODE_REPEAT_ALL = "MODE_REPEAT_ALL";
    String MODE_REPEAT_ONE = "MODE_REPEAT_ONE";
    String MODE_SHUFFLE = "MODE_SHUFFLE";
    String MODE_REPEAT = "MODE_REPEAT";
}
